replicaCount: 1

image:
  repository: ghcr.io/slashnephy/mackerel-operator
  pullPolicy: IfNotPresent
  tag: "@sha256:03b09780b8bb762f475b2318870903eb2d235d79d16f408a1a45c598e435eb25"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

mackerel:
  apiKeySecret:
    name: mackerel-api-key
    key: apiKey

leaderElection:
  enabled: true

policy: upsert-only
ownerID: default
hashLength: 7

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
