replicaCount: 1

image:
  repository: ghcr.io/slashnephy/mackerel-operator
  pullPolicy: IfNotPresent
  tag: "@sha256:551fe2b37a750b365812102c92d3ebdceeb5fb977fd6be9e17261d4d755d2973"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

mackerel:
  apiKeySecret:
    name: mackerel-api-key
    key: apiKey

leaderElection:
  enabled: true

policy: upsert-only
ownerID: default
hashLength: 7

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
