---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mackerel.starry.blue
  resources:
  - externalmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mackerel.starry.blue
  resources:
  - externalmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - mackerel.starry.blue
  resources:
  - externalmonitors/status
  verbs:
  - get
  - patch
  - update
